name: hangman-bot-kt
services:
  db:
    restart: on-failure
    image: mysql:8.4
    volumes:
      - v-database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"

volumes:
  v-database:
